### ISSUE TITLE
Link rollovers are standard text color

### ISSUE THREAD

**Issue by japhb** [lizmat/App-Raku-Log#14]
Links in the logs have a rollover color that is the same as normal text (so the clickability seems to disappear when you're about ready to click).  Standard behavior is instead to have a rollover behavior that keeps the link color, but shows an underline on hover.

**Comment by japhb** [comment]
Not fixed on live site; restart needed?

**Comment by lizmat** [comment]
Looks fixed to me?  Forced reload needed to get fresh stylesheets maybe?
