### ISSUE TITLE
Live view redisplays commit messages

### ISSUE THREAD

**Issue by patrickbkr** [lizmat/App-Raku-Log#20]
It's great that the live view now highlights commit blocks. But I think the following is not intended:

![grafik](https://user-images.githubusercontent.com/6307078/138090900-66616ce3-b914-48fa-a02b-236b04d80681.png)

**Comment by lizmat** [comment]
Should be fixed with https://github.com/lizmat/App-IRC-Log/commit/28448a7775baa6f43db21a9bc324c05ebee9d6cf  and is now also live.
