### ISSUE TITLE
Loading multiple channels at once causes failures

### ISSUE THREAD

**Issue by japhb** [lizmat/App-Raku-Log#30]
If I have 4-5 channel logs open in separate browser tabs (say for instance `#moarvm`, `#raku-dev`, `#raku`, and `#cro`), and quickly `F5` them all, half or more of them will fail with errors after a few seconds.  If I refresh the very same tabs, but space out the `F5`'s by 1-2 seconds a piece, all logs load fine, even though they all appear to be loading in parallel still.

Thus I'm guessing there's some part of the load-and-render process that does not like to be run concurrently.  Space out the requests just enough, and that stage doesn't overlap, and all is good.

**Comment by lizmat** [comment]
OOC, which browser?

What are the errors that you see?

**Comment by japhb** [comment]
Firefox 94.0, 64-bit, on x64 Linux Mint 20.2.

... and of course I can't recreate the errors right now.  Maybe time of day (and thus likely load on your server and/or the relevant parts of the Internet) matters?  I'll check again tomorrow morning, which is when I usually do my catchup backlogging.

**Comment by lizmat** [comment]
Ok, contact me on IRC then... I'd like to see you try while monitoring the log

**Comment by japhb** [comment]
I can no longer reproduce this, so closing for now.

**Comment by lizmat** [comment]
Thanks for following up!
